version: '3.1'

networks:
  app:
    driver: bridge
services:
    webserver:
        image: 'nginx:alpine'
        container_name: "${SERVICE_NAME}_webserver"
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${NGINX_PORT}:80'
        networks:
            - app
    php-fpm:
        build: 'docker/php-fpm'
        container_name: "${SERVICE_NAME}_source"
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - app
    redis:
        image: 'redis:latest'
        container_name: "${SERVICE_NAME}_redis"
        restart: always
        command: redis-server --appendonly yes
        ports:
            - '${REDIS_PORT}:6379'
        networks:
            - app
    supervisor:
        build: 'docker/supervisor'
        working_dir: /app
        container_name: "${SERVICE_NAME}_supervisor"
        volumes:
            - '.:/app'
            - './docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf'
        networks:
            - app
